global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['host.docker.internal:3000']
    metrics_path: /metrics

  - job_name: 'email-worker'
    static_configs:
      - targets: ['host.docker.internal:3002']
    metrics_path: /metrics

  - job_name: 'sms-worker'
    static_configs:
      - targets: ['host.docker.internal:3003']
    metrics_path: /metrics